### ISSUE TITLE
Writing no longer works after updating to version 1.3.3 due to timeout

### ISSUE THREAD

**Issue by fdanapfel** [henols/firestarter_app#11]
After updating firestarter to version 1.3.3 the write command fails with a timeout every time while other commands still work:
```
[frank@Mac:~]% pipx upgrade firestarter 
upgraded package firestarter from 1.3.0 to 1.3.3 (location: /Users/frank/.local/pipx/venvs/firestarter)
[frank@Mac:~]% firestarter --version     
Firestarter version: 1.3.3
[frank@Mac:~]% firestarter blank M27C1001              
EPROM M27C1001 is blank.
[frank@Mac:~]% firestarter write M27C1001 tos_ger_C301937-006_EE.bin
Writing tos_ger_C301937-006_EE.bin to M27C1001
Error: Timeout, no response on /dev/cu.usbmodem146401
Error while writing: Timeout, no response on /dev/cu.usbmodem146401
```
This happens both on macOS (Intel iMac)  and also on Raspberry Pi OS Bookworm (RPI 4).

**Comment by fdanapfel** [comment]
After upgrading firestarter to version 1.3.6 and the firmware to 1.3.5 it is now even worse. 

Not even the blank check works anymore:
```
[frank@Mac:~]% pipx upgrade firestarter
upgraded package firestarter from 1.3.2 to 1.3.6 (location: /Users/frank/.local/pipx/venvs/firestarter)
[frank@Mac:~]% firestarter fw --install  
Reading firmware version...
Current firmware version: 1.3.4, for controller: uno
New firmware version available: 1.3.5, for controller: uno
Installing firmware...
Downloading firmware...
Flashing firmware...
Firmware successfully updated.
[frank@Mac:~]% firestarter fw          
Reading firmware version...
Current firmware version: 1.3.5, for controller: uno
You have the latest firmware version: 1.3.5, for controller: uno
[frank@Mac:~]% firestarter blank M27C1001                              
Error: Timeout, no response on /dev/cu.usbmodem146301
Traceback (most recent call last):
  File "/Users/frank/.local/bin/firestarter", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/frank/.local/pipx/venvs/firestarter/lib/python3.13/site-packages/firestarter/main.py", line 204, in main
    return blank_check(args.eprom)
  File "/Users/frank/.local/pipx/venvs/firestarter/lib/python3.13/site-packages/firestarter/eprom_operations.py", line 292, in blank_check
    resp, info = wait_for_response(ser)
                 ~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/frank/.local/pipx/venvs/firestarter/lib/python3.13/site-packages/firestarter/serial_comm.py", line 204, in wait_for_response
    raise Exception(msg)
Exception: Timeout, no response on /dev/cu.usbmodem146301
[frank@Mac:~]% firestarter write M27C1001 tos_ger_C301937-006_EE.bin 
Writing tos_ger_C301937-006_EE.bin to M27C1001
Error: Timeout, no response on /dev/cu.usbmodem146301---------------------------------| 0.0% 
Error while writing: Timeout, no response on /dev/cu.usbmodem146301
```

**Comment by fdanapfel** [comment]
OK, after unplugging and re-plugging the USB cable now it seems to be working again with version 1.3.6 and fw 1.3.5:
```
[frank@Mac:~]% firestarter blank M27C1001                           
ERROR: Memory is not blank, at 0x000000, value: 0x00
Blank check failed for M27C1001
[frank@Mac:~]% firestarter write -b M27C1001 tos_ger_C301937-006_EE.bin
Writing tos_ger_C301937-006_EE.bin to M27C1001
Address: 0x1FE00 - 0x20000 |████████████████████████████████████████████████████████████| 100.0% - 35.25s

Write complete in: 35.25 seconds
[frank@Mac:~]% firestarter blank M27C1001                              
ERROR: Memory is not blank, at 0x000000, value: 0x00
Blank check failed for M27C1001
[frank@Mac:~]% firestarter read M27C1001 
Reading EPROM M27C1001, saving to M27C1001.bin
Address: 0x1FE00 - 0x20000 |████████████████████████████████████████████████████████████| 100.0% - 14.82s

Read complete in: 14.83 seconds
Data saved to M27C1001.bin
[frank@Mac:~]% diff M27C1001.bin tos_ger_C301937-006_EE.bin 
[frank@Mac:~]%
```

**Comment by henols** [comment]
So it's the blank check that isn't working now?

**Comment by fdanapfel** [comment]
> So it's the blank check that isn't working now?

As mentioned in my previous comment after unplugging and replugging the Arduino USB connection to the Mac after the firmware update the blank check and also reading and writing work again without timeouts.

**Comment by henols** [comment]
Perfect, happy to have fixed it without knowing...
Maybe it was a missmatch between app and fw.

**Comment by henols** [comment]
Thanks for the clarification, will dig into it asap.

**Comment by henols** [comment]
Changed the timeout for responses that do a blank check

**Comment by fdanapfel** [comment]
Thank you! Just verified that it works again with version 1.3.7:
```
[frank@Mac:~]% pipx upgrade firestarter
upgraded package firestarter from 1.3.2 to 1.3.7 (location: /Users/frank/.local/pipx/venvs/firestarter)
[frank@Mac:~]% firestarter blank M27C1001
EPROM M27C1001 is blank.
[frank@Mac:~]%
```

**Comment by henols** [comment]
Awesome! Keep up the good work on reporting buggs!
